apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nest-apps-1
  namespace: app2
spec:
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nest-app